language: node_js
sudo: false
matrix:
  include:
    - node_js: "10"
    - node_js: "8"
    - node_js: "6"
      script:
        - "tap test/scenarios.js"
    - node_js: "4"
      script:
        - "tap test/scenarios.js"
script:
  - "tap test/scenarios.js --100"
