language: node_js
sudo: false
matrix:
  include:
    - node_js: "14"
    - node_js: "12"
    - node_js: "10"
    - node_js: "8"
      script:
        - "tap test/scenarios.js"
script:
  - "tap test/scenarios.js --100"
